<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DNV" name="com.actitime.assertionTest.SoftAssertTest" tests="2" failures="1" timestamp="6 Sep 2019 17:39:52 GMT" time="0.021" errors="0">
  <testcase name="modifyCustomerTest" time="0.001" classname="com.actitime.assertionTest.SoftAssertTest"/>
  <testcase name="createCustomerTest" time="0.020" classname="com.actitime.assertionTest.SoftAssertTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [HDCC] but found [HDFC],
	expected [ICI] but found [ICICI]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [HDCC] but found [HDFC],
	expected [ICI] but found [ICICI]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.actitime.assertionTest.SoftAssertTest.createCustomerTest(SoftAssertTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- createCustomerTest -->
</testsuite> <!-- com.actitime.assertionTest.SoftAssertTest -->
